# Generated by Django 4.2.9 on 2025-09-03 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_patient_user'),
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalencounter',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medical_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalencounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_encounters', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='medicalencounter',
            name='reason_for_visit',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
