# Generated by Django 4.2.9 on 2024-01-25 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calllog',
            name='health_care_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_care_assistant', to=settings.AUTH_USER_MODEL),
        ),
    ]
