# Generated by Django 4.2.9 on 2024-01-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0003_alter_calllog_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='patient_id',
        ),
    ]
