# Generated by Django 4.2.9 on 2024-01-25 22:23

import call_log.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0004_remove_calllog_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Declined', 'Declined'), ('Failed', 'Failed')], default=call_log.models.CallStatus['INITIATED'], max_length=20),
        ),
    ]
