# Generated by Django 4.2.9 on 2024-02-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_log", "0005_alter_calllog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="call_type",
            field=models.CharField(
                choices=[("Video", "Video"), ("Audio", "Audio")],
                default="Video",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="priority",
            field=models.IntegerField(
                choices=[
                    ("4", "Critical"),
                    ("3", "High"),
                    ("2", "Medium"),
                    ("1", "Low"),
                ],
                default="2",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Declined", "Declined"),
                    ("Failed", "Failed"),
                    ("Busy", "Busy"),
                ],
                default="Initiated",
                max_length=20,
            ),
        ),
    ]
