# Generated by Django 4.2.9 on 2024-03-08 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("call_log", "0006_alter_calllog_call_type_alter_calllog_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calllog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
