# Generated by Django 4.2.9 on 2024-03-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("call_log", "0007_calllog_created_at_calllog_updated_at"),
        ("call_log", "0007_calllog_patient"),
    ]

    operations = []
