# Generated by Django 4.2.9 on 2024-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_log", "0008_merge_20240308_1417"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="decline_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
