# Generated by Django 4.2.9 on 2024-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("call_log", "0009_calllog_decline_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="meeting_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
