# Generated by Django 4.2.9 on 2025-09-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('call_log', '0010_calllog_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='medical_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication.medicalencounter'),
        ),
    ]
