# Generated by Django 4.2.9 on 2025-09-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_log', '0011_calllog_medical_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='medical_note',
            new_name='medical_encounter',
        ),
    ]
