# Generated by Django 4.2.9 on 2024-02-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_patientrecord_medicalrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientrecord",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
