# Generated by Django 4.2.9 on 2024-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_patientrecord_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="blood_type",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="chronic_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="current_medications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="family_medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="immunization_record",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="medical_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patientrecord",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="MedicalRecord",
        ),
    ]
