# Generated by Django 4.2.9 on 2024-02-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_patientrecord_allergies_patientrecord_blood_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("personnel", "Personnel"), ("doctor", "Doctor")],
                default="personnel",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PatientRecord",
        ),
    ]
