# Generated by Django 4.2.9 on 2024-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
