# Generated by Django 4.2.9 on 2024-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
