# Generated by Django 4.2.9 on 2024-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                editable=False, max_length=15, unique=True, null=True, blank=True
            ),
            preserve_default=False,
        ),
    ]
