# Generated by Django 4.2.9 on 2024-08-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("personnel", "Personnel"),
                    ("doctor", "Doctor"),
                    ("customer", "Customer"),
                ],
                default="personnel",
                max_length=20,
            ),
        ),
    ]
