# Generated by Django 4.2.9 on 2024-09-06 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('flw_ref', models.CharField(max_length=100, unique=True)),
                ('order_ref', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
