# Generated by Django 4.2.9 on 2024-09-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_bvn_wallet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wallet",
        ),
    ]
