# Generated by Django 4.2.9 on 2024-09-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_delete_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="insurance_coverage",
            field=models.CharField(
                blank=True,
                choices=[("health_spring", "Healthspring")],
                max_length=20,
                null=True,
            ),
        ),
    ]
