# Generated by Django 4.2.9 on 2024-09-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_insurance_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
    ]
