# Generated by Django 4.2.9 on 2024-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insurance_coverage',
            field=models.CharField(blank=True, choices=[('health_spring', 'Healthspring'), ('innoson_vehicle_manufacturing', 'Innoson Vehicle Manufacturing'), ('chelsea_group', 'Chelsea Group'), ('newport', 'Newport'), ('angeles_hotel', 'Angeles Hotel')], max_length=50, null=True),
        ),
    ]
