# Generated by Django 4.2.9 on 2025-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_insurance_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='insurance_coverage',
            field=models.CharField(blank=True, choices=[('health_spring', 'Healthspring'), ('innoson_vehicle_manufacturing', 'Innoson Vehicle Manufacturing'), ('chelsea_group', 'Chelsea Group'), ('newport', 'Newport'), ('angeles_hotel', 'Angeles Hotel'), ('24Telemed', 'Telemed 24'), ('Sims_Nigeria', 'Sims Nigeria')], max_length=50, null=True),
        ),
    ]
