# Generated by Django 4.2.9 on 2024-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                default="012345678901", editable=False, max_length=11, unique=True
            ),
            preserve_default=False,
        ),
    ]
