# Generated by Django 4.2.9 on 2024-03-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patientaccesslog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientaccesslog",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
