# Generated by Django 4.2.9 on 2024-09-08 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_transaction_amount_alter_wallet_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
